### 行首如果存在注释符号 "#" 则说明该项 “未启用”

 input-conf = "~~/input.conf"
 include = "~~/profiles.conf"
 use-filedir-conf = yes



 ########
 # 基础 #
 ########

 vo = gpu-next
 gpu-context = d3d11

 hwdec = auto-copy
 hwdec-codecs = h264,hevc,vp8,vp9,av1,ffv1



 ########
 # 功能 #
 ########

# 播放完毕窗口保持运行
 idle = yes
 keep-open = yes

# 禁用输入法
 input-ime = no

# 禁用内置快捷键
 input-builtin-bindings = no

# 关闭跳转丢帧,避免音画不同步
 hr-seek-framedrop = no

# 退出时保存播放进度
 save-position-on-quit = yes
 resume-playback = yes
 resume-playback-check-mtime = yes
 watch-later-options = start,vid,aid,sid

# HDR
 target-colorspace-hint = yes
 target-colorspace-hint-mode = source

# 自动载入当前播放媒体文件所在目录下的所有同类型媒体文件，依名称排序
 autocreate-playlist = same
 directory-mode = ignore
 directory-filter-types = video,audio
 video-exts = avi,flv,m2ts,mkv,mov,mp4,ts,wmv
 image-exts = avif,bmp,jpeg,jpg,jxl,png,webp
 audio-exts = aiff,ape,flac,mp3,ogg,opus,wav

# 如果视频分辨率小于屏幕分辨率的 50%，mpv 会自动将窗口放大到屏幕的 50% 大小
 autofit-smaller = 50%x50%

# 关闭高分屏（如 4K 显示器）下的窗口自动缩放
 hidpi-window-scale = no

# 禁用窗口大小自动调整
 auto-window-resize = no

# 前端读取缓存设置为 1GB
 demuxer-max-bytes = 1024MiB
 
# 允许向后缓存 512MB
 demuxer-max-back-bytes = 512MiB

# 缓存存放位置
 icc-cache-dir = "~~/cache"
 gpu-shader-cache-dir = "~~/cache"
 watch-later-dir = "~~/cache"

#关闭播放器窗口的原生边框，实现无边框窗口效果
 border = no

#将播放列表设置为无限循环播放
 loop-playlist = inf

# 窗口自动吸附
 snap-window = yes

# 禁用播放器内置的统计信息
 load-stats-overlay = no
 
# 关闭 mpv 自带的 OSC (On Screen Controller) 屏幕控制器
 osc = no

# OSD信息提示 0=关闭所有
 osd-level = 0



 ########
 # 音频 #
 ########

# 强制 mpv 使用 Windows 的 WASAPI 音频接口
 ao = wasapi

# 默认音量为 100
 volume = 100

# 最大音量为 130
 volume-max = 130

# 强制将所有音频输出为立体声
 audio-channels = stereo

# 自动加载同目录下的外挂音频文件（如单独的 .flac 或 .mka 音轨）
 audio-file-auto = fuzzy
 
# 保存当前音量设置
 script-opts-append = save_global_props-props=volume,mute



 ########
 # 视频 #
 ########

# 自动读取并应用 Windows 系统的显示器 ICC 校色文件
# icc-profile-auto = yes

# 通过微调音频的采样率，让视频帧率完美匹配显示器的刷新率
 video-sync = display-resample

# 开启运动补偿（插帧）。当视频帧率与显示器刷新率不匹配时（如 24fps 在 60Hz 屏幕），mpv 会通过算法生成中间帧来填补
 interpolation = yes

# 时间缩放算法，配合插帧使用。sphinx 画质极高但性能开销大
#tscale = sphinx

# 视频放大和色度缩放算法，bilinear 是最基础、性能消耗最低的算法
 cscale = bilinear
 scale = bilinear

# 视频缩小算法，bicubic 在缩小高分辨率视频（如 4K 缩到 1080p 窗口）时能保留较好的细节
 dscale = bicubic

# Sigmoid 放大校正。能减少放大视频时产生的“光晕”伪影，让边缘更自然
 sigmoid-upscaling = no

# 缩小校正。在缩小视频时进行多次采样，防止摩尔纹和细节丢失
 correct-downscaling = no

# 抖动处理，用于减少色彩断层（色带）
 dither-depth = auto

# 自动反交错（去拉丝），播放老旧的隔行扫描视频（如早期的电视录像、DVD）时，自动消除水平条纹
 deinterlace = auto



 ########
 # 字幕 #
 ########

# 自动加载外部字幕文件，使用“模糊匹配”模式
 sub-auto = fuzzy

# 如果字幕乱码，mpv 会尝试用 UTF-8 或 GB18030 自动修复
 sub-codepage = UTF-8:GB18030

# 设置字幕语言的优先级
 slang = chs,sc,zh-cn,chi,zh,zh-tw,cht,zho,ze

# 当首选语言的字幕不可用时，允许回退到其他语言的字幕
 subs-fallback = yes

# 将字幕混合到视频帧中进行渲染，字幕会和视频画面一起进行色彩管理和缩放，保证字幕的分辨率与画面一致，避免“画面模糊字幕高清”的情况
 blend-subtitles = yes

# 设置字幕在 HDR 视频中的峰值亮度为 100
 sub-hdr-peak = 100

# 字幕字体
 sub-font = "思源黑体 Bold"

# 字幕字体大小
 sub-font-size = 44
 
# 对 ASS 字幕中的“标志/图标”进行缩放
 sub-scale-signs = yes

# 设置字幕描边（轮廓）宽度
 sub-outline-size = 4

# 设置纯文本字幕的颜色
 sub-color = "#FFD766"

# 允许纯文本字幕显示在视频的黑边上
 sub-use-margins = yes

# 强制外挂的 ASS 字幕也允许显示在黑边上
 sub-ass-force-margins = yes

# 设置图像字幕（如蓝光原盘的 PGS 字幕）在 HDR 视频中的峰值亮度为 10000
 image-subs-hdr-peak = 10000

# 在使用 yt-dlp 抓取网络视频字幕时，排除（过滤）掉名为 danmaku 的字幕轨道
 ytdl-raw-options-append = sub-langs=-danmaku



 ########
 # 截图 #
 ########

# 设置默认的截图格式为 PNG
 screenshot-format = png

# 设置 PNG 的压缩等级为 4（范围 0-9）
 screenshot-png-compression = 4

# 当使用 WebP 格式截图时，强制开启无损模式
 screenshot-webp-lossless = yes

# 不在截图文件中嵌入色彩空间（Color Space）
 screenshot-tag-colorspace = no

# 关闭高位深截图
 screenshot-high-bit-depth = no

# 截图会保存在桌面
 screenshot-template = "~~desktop/MPV-%P-N%n"
