# 滚动弹幕的显示时间
duration_marquee=12
# 固定弹幕的显示时间
duration_still=6
#字体(名称两边不需要使用引号""括住)
font_name=思源黑体 Bold
#大小
font_size=50
#全部弹幕的显示范围(0-100)
reserve_bottom=85
#透明度
alpha=0.6
# 弹幕过多自动删减 true/false
reduce_comment=false