#滚动弹幕的显示时间
scrolltime=12
#固定弹幕的显示时间
fixtime=5
#字体(名称两边不需要使用引号""括住)
fontname=思源黑体 Bold
#大小
fontsize=50
#阴影
shadow=0
#粗体
bold=yes
#全部弹幕的显示范围(0.0-1.0)
displayarea=0.85
#描边 0-4
outline=1
#透明度
opacity=0.6